### ISSUE TITLE
插件上传图片报错

### ISSUE THREAD

**Issue by Chinafrfq** [Redns/picgo-plugin-imgtp#3]
我的插件配置：
![image](https://github.com/Redns/picgo-plugin-imgtp/assets/105155111/4b8868e8-cefc-4c1b-bf76-9ca7e304e3e2)

我可以确定账号和密码没错，我特意去重新登录了，很懵逼

typora上传报错，错误日志：
2023-09-09 12:20:12 [PicGo ERROR] 
------Error Stack Begin------
Error: [IMGTP] 获取 login token 失败，服务器返回状态码 undefined
    at Object.handle (C:\Users\ghp\AppData\Roaming\picgo\node_modules\picgo-plugin-imgtp\src\index.js:240:23)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Lifecycle.doUpload (D:\ruanjian\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:80:9)
    at async Lifecycle.start (D:\ruanjian\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\Lifecycle.js:26:13)
    at async PicGo.upload (D:\ruanjian\PicGo\resources\app.asar\node_modules\picgo\dist\src\core\PicGo.js:205:32)
    at async Object.upload (D:\ruanjian\PicGo\resources\app.asar\background.js:36:29196)
    at async Pt (D:\ruanjian\PicGo\resources\app.asar\background.js:36:31625)
    at async D:\ruanjian\PicGo\resources\app.asar\background.js:36:32625
-------Error Stack End------- 
2023-09-09 12:20:12 [PicGo WARN] [PicGo Server] upload failed, see picgo.log for more detail ↑

**Comment by Redns** [comment]
因为 `PicGo` 从 `v2.3.1` 开始调整了插件接口，为了适配新版本插件同步进行了更新，所以需要将 `PicGo` 更新至 `v2.3.1+` 才能正常使用哈

**Comment by Chinafrfq** [comment]
好的，感谢，明白了
